### ISSUE TITLE
Icons not showing / rendering properly for hosted version

### ISSUE THREAD

**Issue by marcus-d5r** [GatsbyCentral/gatsby-v2-starter-lumen#5]
Hello,

thanks a lot for providing this nice template.

I am having issues with the icons. 

When I run `Gatsby develop` or `Gatsby build` the icons render fine. 
However, when I deploy to "production" then the icons do not render properly anymore. Mail and Telegram icon seem to work, but the rest not.

See here for an example with icons not working: http://tremendous-spoon.surge.sh/

This is an untouched Lumen template, built with "Gatsby build" and then deployed to surge via Command Line. The same issue I have when I deploy it to netlify.

The icons are rendered in the component `Links` , called from the `Sidebar` component.

The icons come from assets folder CSS (see screenshot below, and link to source here: https://github.com/GatsbyCentral/gatsby-v2-starter-lumen/tree/master/src/assets/fonts/fontello-771c82e0 ).

In the readme for Fontello font it says

>  Attention for server setup 
> You MUST setup server to reply with proper `mime-types` for font files -
> otherwise some browsers will fail to show fonts.

Might this be the issue? If so, would I have to configure something within Gatsby build or would it have something to do with the hoster, e.g. surge or netlify?
Any ideas where this comes from and what might resolve the issue?

Thanks!

![image](https://user-images.githubusercontent.com/34041543/57743244-e4a31180-7689-11e9-8afc-6c9556d42ac6.png)

**Comment by chmac** [comment]
You mean the icons bottom right in the sidebar? They load fine for me on the link you posted:

<img width="131" alt="Screenshot 2019-05-15 at 22 57 57" src="https://user-images.githubusercontent.com/690997/57809047-fd342a00-7764-11e9-93b8-ba4eb3ad3831.png">

If you mean something else, please feel free to reopen this issue and post more info.

Maybe the problem is on your browser somehow?
