### ISSUE TITLE
Starter fails to build due to misconfiguration of sitemap plugin

### ISSUE THREAD

**Issue by eyalroth** [GatsbyCentral/gatsby-v2-starter-lumen#6]
Trying to build the starter fails with this error:
```
error Plugin gatsby-plugin-sitemap returned an error

  Error: SiteMetaData 'siteUrl' property is required. Check out the documentation to see a working example: https://www.
  gatsbyjs.org/packages/gatsby-plugin-sitemap/#how-to-use

  - internals.js:43
    [blog-gatsby]/[gatsby-plugin-sitemap]/internals.js:43:13
```

It is probably better to delete the custom options for both the sitemap and feed plugins and rely on the defaults, which will require adding both `siteUrl` and `description` fields to the site metadata.

**Comment by msrinathr** [comment]
Please change url to siteurl at line #6 in gatsby-config.js

module.exports = {
  siteMetadata: {
    siteurl: 'https://lumen.netlify.com',
    title: 'Blog by John Doe',
